let product = [
    {
        name:'Herschel supply co 25l',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-02.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'92.00',
        img:'productImg/item-03.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Featured'],
    },
    {
        name:'Coach slim easton black',
        'old price':null,
        'new price':'165.00',
        img:'productImg/item-05.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Frayed denim shorts',
        'old price':'29.50',
        'new price':'165.00',
        img:'productImg/item-07.jpg',
        tag:null,
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-01.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-14.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Featured','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-06.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Sale'],
    },
    {
        name:'Denim jacket blue',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Coach slim easton black',
        'old price':'new',
        'new price':'165.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-02.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'92.00',
        img:'productImg/item-03.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Featured'],
    },
    {
        name:'Coach slim easton black',
        'old price':null,
        'new price':'165.00',
        img:'productImg/item-05.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Frayed denim shorts',
        'old price':'29.50',
        'new price':'165.00',
        img:'productImg/item-07.jpg',
        tag:null,
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-01.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-14.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Featured','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-06.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Sale'],
    },
    {
        name:'Denim jacket blue',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Coach slim easton black',
        'old price':'new',
        'new price':'165.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-02.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'92.00',
        img:'productImg/item-03.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Featured'],
    },
    {
        name:'Coach slim easton black',
        'old price':null,
        'new price':'165.00',
        img:'productImg/item-05.jpg',
        tag:"sale",
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Frayed denim shorts',
        'old price':'29.50',
        'new price':'165.00',
        img:'productImg/item-07.jpg',
        tag:null,
        liked:false,
        'added to card':false,
        category:['Best Seller','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-01.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },
    {
        name:'Denim jacket blue',
        'old price':null,
        'new price':'75.00',
        img:'productImg/item-14.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Featured','Top Rate'],
    },
    {
        name:'Herschel supply co 25l',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-06.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Sale'],
    },
    {
        name:'Denim jacket blue',
        'old price':'new',
        'new price':'75.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Sale','Top Rate'],
    },
    {
        name:'Coach slim easton black',
        'old price':'new',
        'new price':'165.00',
        img:'productImg/item-08.jpg',
        tag:'new',
        liked:false,
        'added to card':false,
        category:['Best Seller','Featured'],
    },




]